### ISSUE TITLE
[plugin issue] / Kodi Leia 18 alpha1-x64 (Win10) / 

### ISSUE THREAD

**Issue by akiwatti** [Twilight0/script.module.streamlink.base#3]
x  This is a bug report.

related to update/patch: https://github.com/streamlink/streamlink/issues/1669  ( vidio.py)
- plugin vidio.com  

(1) Kodi_Win10: kodi-18.0-Leia_alpha1-x64.exe
17:05:26.047 T:14284  NOTICE: ADDON: script.module.streamlink.base v2018.05.21 installed
17:05:26.048 T:14284  NOTICE: ADDON: script.module.streamlink.crypto v1.4.0 installed
17:05:26.048 T:14284  NOTICE: ADDON: service.streamlink.proxy v4.1.1 installed
17:05:26.048 T:14284  NOTICE: ADDON: script.module.streamlink.plugins v1.0.3 installed

(2) m3u call used at PVR "IPTV simple client" addon:
#EXTINF:-1 tvg-shift="0" tvg-id="RCTI" tvg-logo="rcti.png",RCTI (not working streamlink)
http://127.0.0.1:50165/?url=https%3A%2F%2Fwww.vidio.com/live/665-rcti-tv-stream

(3) KODI-.log
17:06:36.411 T:1668  NOTICE: Creating InputStream
17:06:40.249 T:3224   ERROR: Traceback (most recent call last):
17:06:40.249 T:3224   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 290, in _handle_request_noblock
17:06:40.251 T:3224   ERROR:     self.process_request(request, client_address)
17:06:40.251 T:3224   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 318, in process_request
17:06:40.251 T:3224   ERROR:     self.finish_request(request, client_address)
17:06:40.251 T:3224   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 331, in finish_request
17:06:40.251 T:3224   ERROR:     self.RequestHandlerClass(request, client_address, self)
17:06:40.251 T:3224   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 652, in __init__
17:06:40.251 T:3224   ERROR:     self.handle()
17:06:40.251 T:3224   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\BaseHTTPServer.py", line 340, in handle
17:06:40.252 T:3224   ERROR:     self.handle_one_request()
17:06:40.252 T:3224   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\BaseHTTPServer.py", line 328, in handle_one_request
17:06:40.252 T:3224   ERROR:     method()
17:06:40.252 T:3224   ERROR:   File "C:\Users\******\AppData\Roaming\Kodi\addons\service.streamlink.proxy\resources\lib\service.py", line 118, in do_GET
17:06:40.253 T:3224   ERROR:     res = session.http.get(stream.url)
17:06:40.253 T:3224   ERROR:   File "C:\Users\******\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\sessions.py", line 521, in get
17:06:40.254 T:3224   ERROR:     return self.request('GET', url, **kwargs)
17:06:40.254 T:3224   ERROR:   File "C:\Users\******\AppData\Roaming\Kodi\addons\script.module.streamlink.base\resources\lib\streamlink\plugin\api\http_session.py", line 175, in request
17:06:40.254 T:3224   ERROR:     raise err
17:06:40.254 T:3224   ERROR: PluginError: Unable to open URL: https://kmklive-lh.akamaihd.net/i/rcti_ta_regular@94478/index_360_av-p.m3u8?sd=10&rebase=on&hdntl=exp=1527951998~acl=%2fi%2f*~data=hdntl~hmac=12937a0816e176ce9591246feddf235df67c071e54dc0946c010e28daa0643d5 (403 Client Error: Forbidden for url: https://kmklive-lh.akamaihd.net/i/rcti_ta_regular@94478/index_360_av-p.m3u8?sd=10&rebase=on&hdntl=exp=1527951998~acl=%2fi%2f*~data=hdntl~hmac=12937a0816e176ce9591246feddf235df67c071e54dc0946c010e28daa0643d5)
17:06:40.255 T:1668   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
17:06:40.255 T:1668   ERROR: CCurlFile::Open failed with code 0 for http://127.0.0.1:50165/?url=https%3A%2F%2Fwww.vidio.com/live/665-rcti-tv-stream
17:06:40.255 T:1668   ERROR: XFILE::CFileCache::Open - failed to open source <http://127.0.0.1:50165/?url=https%3A%2F%2Fwww.vidio.com/live/665-rcti-tv-stream>

**Comment by Twilight0** [comment]
I will probably have to update this library to reflect last changes from upstream in order to have clear picture of the issue. You can also use the tester addon found in my [other repo](https://github.com/Twilight0/plugin.video.streamlink-tester).

**Comment by akiwatti** [comment]
Thanks @Twilight0 for picking up issue...

symptoms on Kodi Leila 18 / Raspberry Pi3 / libreelec:
- NOTICE: Starting Kodi (18.0-ALPHA2 Git:795b10a). Platform: Linux ARM 32-bit
- NOTICE: Using Release Kodi x32 build (version for Raspberry Pi)
- NOTICE: Kodi compiled Jun  1 2018 by GCC 7.3.0 for Linux ARM 32-bit version 4.14.44 (265772)
- NOTICE: Running on LibreELEC (Milhouse): devel-20180601210455-#0601-g19b9bed [Build #0601] 9.0, kernel: Linux ARM 32-bit version 4.14.44
- NOTICE: FFmpeg version/source: 4.0-Kodi

plugin.video.streamlink-tester:
Test-URL: https://www.vidio.com/live/665-rcti-tv-stream

Kodi.log:
09:09:47.221 T:1385636720   ERROR: NEWADDON Unknown Video Info Key "action"
09:09:47.221 T:1385636720   ERROR: NEWADDON Unknown Video Info Key "isfolder"
09:09:47.221 T:1385636720   ERROR: NEWADDON Unknown Video Info Key "url"
09:09:47.222 T:1385636720   ERROR: NEWADDON Unknown Video Info Key "action"
09:09:47.222 T:1385636720   ERROR: NEWADDON Unknown Video Info Key "isfolder"
09:09:47.222 T:1385636720   ERROR: NEWADDON Unknown Video Info Key "url"
09:10:06.773 T:1385636720   ERROR: EXCEPTION: argument "message" for method "notification" must be unicode or str
09:10:19.128 T:1938247696   ERROR: Previous line repeats 3 times.
09:10:19.128 T:1938247696   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.streamlink-tester/?action=play&url=https%3A%2F%2Fwww.vidio.com%2Flive%2F665-rcti-tv-stream%0D&title=https%3A%2F%2Fwww.vidio.com%2Flive%2F665-rcti-tv-stream%0D]
09:10:26.098 T:1385636720   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'find'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.streamlink-tester/main.py", line 27, in <module>
                                                player.play(url)
                                              File "/storage/.kodi/addons/plugin.video.streamlink-tester/resources/lib/modules/player.py", line 55, in play
                                                directory.resolve(router(url))
                                              File "/storage/.kodi/addons/plugin.video.streamlink-tester/resources/lib/modules/player.py", line 30, in router
                                                plugin = session.resolve_url(url)
                                              File "/storage/.kodi/addons/script.module.streamlink.base/resources/lib/streamlink/session.py", line 364, in resolve_url
                                                url = update_scheme("http://", url)
                                              File "/storage/.kodi/addons/script.module.streamlink.base/resources/lib/streamlink/utils/__init__.py", line 150, in update_scheme
                                                target_p = urlparse(target)
                                              File "/usr/lib/python2.7/urlparse.py", line 143, in urlparse
                                              File "/usr/lib/python2.7/urlparse.py", line 182, in urlsplit
                                            AttributeError: 'NoneType' object has no attribute 'find'
                                            -->End of Python script error report<--
09:10:26.523 T:1938247696   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.streamlink-tester/?action=play&url=&title=]

**Comment by akiwatti** [comment]
Hello  @Twilight0, 
sorry for bothering you, but am I right, you're still checking a this issue of streamlink plugins (e.g vidio.py) URL handover to Kodi "PVR.iptvsimple", aren't you?  related to your repo with "service.streamlink.proxy; script.module.streamlink.base".
Thanks in advance.

**Comment by Twilight0** [comment]
I 've just tested the url you provided and I am getting the following error:

    ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <class 'streamlink.exceptions.PluginError'>
    Error Contents: Unable to validate response text: Unable to validate key 'token': Type of u'GAZIASFPecOO/m9RAPRA+t6HAN8fvbLOxOQiaF652G0zxfBI6r73KGEb8Zk6gb3Brgg+oVsnLsn7VV5v4ulC9Q==' should be 'str' but is 'unicode'
    Traceback (most recent call last):
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.streamlink-tester\main.py", line 27, in <module>
        player.play(url)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.streamlink-tester\resources\lib\modules\player.py", line 92, in play
        stream = router(url)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\plugin.video.streamlink-tester\resources\lib\modules\player.py", line 38, in router
        streams = plugin.streams()
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugin\plugin.py", line 301, in streams
        ostreams = self._get_streams()
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugins\vidio.py", line 49, in _get_streams
        tokens = self.get_url_tokens(stream_id)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugins\vidio.py", line 33, in get_url_tokens
        csrf_token = self.get_csrf_tokens()
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugins\vidio.py", line 29, in get_csrf_tokens
        schema=self.token_schema)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.requests\lib\requests\sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugin\api\http_session.py", line 180, in request
        res = schema.validate(res.text, name="response text", exception=PluginError)
    File "P:\GitHub\Testers\Krypton\Kodi\portable_data\addons\script.module.streamlink.base\resources\lib\streamlink\plugin\api\validate.py", line 484, in validate
        raise exception("Unable to validate {0}: {1}".format(name, err))
    PluginError: Unable to validate response text: Unable to validate key 'token': Type of u'GAZIASFPecOO/m9RAPRA+t6HAN8fvbLOxOQiaF652G0zxfBI6r73KGEb8Zk6gb3Brgg+oVsnLsn7VV5v4ulC9Q==' should be 'str' but is 'unicode'
    -->End of Python script error report<--

The regular streamlink from upstream's implementation works ok, but the error is produced only on Kodi... will investigate.

**Comment by Twilight0** [comment]
Version 2018.06.10 has updated vidio plugin, however it requires headers to be passed into Kodi's ffmpeg which version 1.2.0 of Streamlink Tester is able to append. I don't know how it can work with IPTV Simple Client + localhost proxy, at least not yet.

**Comment by akiwatti** [comment]
Hello @Twilight0 , your addons seems now catched an bug.. e.g. your latest proxy addon throws lot of error messages..before was working at kodi pvr iptvsimple with streamlink plug dailymotion.py..now in kodi.log threats..
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named ordereddict

**Comment by Twilight0** [comment]
Fixed on 2018.06.10.1... But please create separate issue threads for non-related matters.
